### PR TITLE
GroupedSensor

### PR DESCRIPTION
**Pull request by bhelm**
I have already wrote this before i realized that there is already an unfinished looking repository for this. So here is my version with Average/Min/Max feature.

image

Thank you for your work on this project, it is a pleasure to use it!

Im just a bit confused on whenever it should be called cbpi4-GroupedSensor or cbpi4_GroupedSensor. I did go for the - as most other plugins also follow this schema.

### CODE REVIEW

**Comment by avollkopf** [comment]
Unfortunately, pkugin name and file names have changed. I can't merge this directly, but will update the code accordingly.

Initially, I started to name all plugins with '-'. Back in March, Manuel did a change where you just run the command 'cbpi create' to create a plugin. It_'ll ask for a name and adds cbpi4_ as prefix

Alex

**Comment by avollkopf** [comment]
Last update should address the requested changes: https://github.com/avollkopf/cbpi4_GroupedSensor/commit/620ca87ea95d400e55a2cb5e7c694c11454b36d2 and keeps the plugin name

**Comment by bhelm** [comment]
Thank you. There is still a bug left on the master (Actor vs Sensor):

image

**Comment by avollkopf** [comment]
Fixed: https://github.com/avollkopf/cbpi4_GroupedSensor/commit/7d13009b38f97f23a0c7c0b464f0789c8dde8465

**Pull request closed without merging**
